## 6.- Creating NumPy arrays

In [4]:
import numpy as np

def test_run():
  # list to 1D array
  print(np.array([(2,3,4), (5,6,7)]))

if __name__=="__main__":
  test_run()

[[2 3 4]
 [5 6 7]]


## 7.- Arrays with initial values

In [7]:
import numpy as np

def test_run():
  # Empty array
  #print(np.empty(5))
  #print(np.empty((5,4,3)))
  print(np.ones((5,4)))

if __name__=="__main__":
  test_run()

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 8.- Specify the datatype

In [8]:
import numpy as np

def test_run():
  # Array 1s
  print(np.ones((5,4), dtype=np.int_))

if __name__=="__main__":
  test_run()

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
