## 6.- Creating NumPy arrays

In [ ]:
import numpy as np

def test_run():
  # list to 1D array
  print(np.array([(2,3,4), (5,6,7)]))

if __name__=="__main__":
  test_run()

[[2 3 4]
 [5 6 7]]


## 7.- Arrays with initial values

In [ ]:
import numpy as np

def test_run():
  # Empty array
  #print(np.empty(5))
  #print(np.empty((5,4,3)))
  print(np.ones((5,4)))

if __name__=="__main__":
  test_run()

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 8.- Specify the datatype

In [ ]:
import numpy as np

def test_run():
  # Array 1s
  print(np.ones((5,4), dtype=np.int_))

if __name__=="__main__":
  test_run()

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## 9.- Generating random numbers

In [ ]:
import numpy as np

def test_run():
  # Array 1s
  #print(np.random.rand(5, 4))
  print(np.random.randint(10))
  print(np.random.randint(0, 10))
  print(np.random.randint(0, 10, size=5))
  print(np.random.randint(0, 10, size=(2,3)))

if __name__=="__main__":
  test_run()

5
2
[1 6 0 7 4]
[[2 8 2]
 [1 0 7]]


## 10.- Array atributes

In [ ]:
import numpy as np

def test_run():
  # Array 1s
  a = np.random.random((5, 4))
  print(a.size)
  print(a.dtype)

if __name__=="__main__":
  test_run()

20
float64


## 11.- Operations on ndarrays

In [ ]:
import numpy as np

def test_run():
  
  np.random.seed(693)  # seed the random number generator 
  a = np.random.randint(0, 10, size=(5, 4))  # 5x4 random integers in [0, 10] 
  print("Array:\n", a)

  # Sum of all elements
  # print("Sum of all elements:", a.sum())

  # Statistics: min, max, mean (across rows, cols, and overall)
  print("Minimum of each column:\n", a.min(axis=0))
  print("Maximum of each row:\n", a.max(axis=1))
  print("Mean of each column:\n", a.mean())

if __name__=="__main__":
  test_run()

Array:
 [[2 0 5 1]
 [1 3 4 4]
 [9 2 9 1]
 [9 3 7 5]
 [4 7 0 3]]
Minimum of each column:
 [1 0 0 1]
Maximum of each row:
 [5 4 9 9 7]
Mean of each column:
 3.95


## 12.- Locate maximum value

In [ ]:
"""Locate maximum value."""

import numpy as np


def get_max_index(a):
    """Return the index of the maximum value in given 1D array."""
    # TODO: Your code here
    return (np.where(a == a.max()))[0][0]


def test_run():
    a = np.array([9, 6, 2, 3, 12, 14, 7, 10], dtype=np.int32)  # 32-bit integer array
    print("Array:", a)
    
    # Find the maximum and its index in array
    print("Maximum value:", a.max())
    print("Index of max.:", get_max_index(a))


if __name__ == "__main__":
    test_run()


Array: [ 9  6  2  3 12 14  7 10]
Maximum value: 14
Index of max.: 5


## 13.- Timing python operations

In [ ]:
"""Using time function."""

import numpy as np
from time import time

def how_long(func, *args):
  """Execute function with given arguments, and measure execution time."""
  t0 = time()
  result = func(*args)
  t1 = time()
  return result, t1 - t0


def manual_mean(arr):
  """Compute mean (average) of all elements in the given 2D array."""
  sum = 0
  for i in range(0, arr.shape[0]):
    for j in range(0, arr.shape[1]):
      sum = sum + arr[i, j]
  return sum / arr.size

def numpy_mean(arr):
  """Compute mean (average) using NumPy."""
  return arr.mean()

def test_run():
    """Function called by Test Run."""
    nd1 = np.random.random((1000, 10000)) # Use a sufficiently large array

    # Time the two fuctions, retrieving results and execution times
    res_manual, t_manual = how_long(manual_mean, nd1)
    res_numpy, t_numpy = how_long(numpy_mean, nd1)
    print("Manual: {:.6f} ({:.3f} secs.) vs. Numpy: {:.6f} ({:.3f} secs.)".format(res_manual, t_manual, res_numpy, t_numpy))

    # Make sure both give us the same answer (Upto some precision)
    assert abs(res_manual - res_numpy) <= 10e-6, "Results aren't equal!"

    # Compute speedup
    speedup = t_manual / t_numpy
    print("NumPy mean is", speedup, "times faster than manual for loops.")


if __name__ == "__main__":
    test_run()


Manual: 0.500042 (2.192 secs.) vs. Numpy: 0.500042 (0.007 secs.)
NumPy mean is 298.53014316787323 times faster than manual for loops.


## 15.- Accessing array elements

In [3]:
import numpy as np

def test_run():
  """Accessing array elements"""

  a = np.random.rand(5, 4)
  print("Array:\n", a)

  # Accesing element at position 3, 2
  element = a[3, 2]
  print("\nElement:\n", element)

  # Elements in defined range
  print("\nRange of elements\n", a[0, 1:3])

  print("\nSelect 0, 2 columns in every row\n", a[:, 0:3:2])


if __name__ == "__main__":
  test_run()

Array:
 [[0.36198112 0.63510595 0.85258348 0.22626681]
 [0.64857751 0.49531023 0.43719975 0.84038224]
 [0.16204284 0.47775164 0.80543268 0.69033607]
 [0.56128447 0.90073824 0.13074922 0.77265745]
 [0.58753115 0.62369619 0.50648834 0.77301163]]

Element:
 0.13074921930976158

Range of elements
 [0.63510595 0.85258348]

Select 0, 2 columns in every row
 [[0.36198112 0.85258348]
 [0.64857751 0.43719975]
 [0.16204284 0.80543268]
 [0.56128447 0.13074922]
 [0.58753115 0.50648834]]


## 16.-Modifiying array elements

In [5]:
import numpy as np

def test_run():
  """Accessing array elements"""

  a = np.random.rand(5, 4)
  print("Array:\n", a)

  # Assingning a value to a particular location
  a[0,0] = 1
  print("\nSingle value changed\n",a)

  # Assingning a value to an entire row
  a[0,:] = 2
  print("\nEntire row changed\n",a)

  # Assingning a list a column in an array
  a[:,3] = [1, 2, 3, 4, 5]
  print("\nEntire row changed\n",a)

if __name__ == "__main__":
  test_run()

Array:
 [[0.1446725  0.91136213 0.4202858  0.0914508 ]
 [0.25632288 0.60735912 0.83134689 0.44763118]
 [0.19181139 0.03368897 0.24926656 0.70121421]
 [0.29864255 0.03262925 0.94542109 0.11536893]
 [0.83587524 0.20914719 0.33298469 0.46639359]]

Single value changed
 [[1.         0.91136213 0.4202858  0.0914508 ]
 [0.25632288 0.60735912 0.83134689 0.44763118]
 [0.19181139 0.03368897 0.24926656 0.70121421]
 [0.29864255 0.03262925 0.94542109 0.11536893]
 [0.83587524 0.20914719 0.33298469 0.46639359]]

Entire row changed
 [[2.         2.         2.         2.        ]
 [0.25632288 0.60735912 0.83134689 0.44763118]
 [0.19181139 0.03368897 0.24926656 0.70121421]
 [0.29864255 0.03262925 0.94542109 0.11536893]
 [0.83587524 0.20914719 0.33298469 0.46639359]]

Entire row changed
 [[2.         2.         2.         1.        ]
 [0.25632288 0.60735912 0.83134689 2.        ]
 [0.19181139 0.03368897 0.24926656 3.        ]
 [0.29864255 0.03262925 0.94542109 4.        ]
 [0.83587524 0.20914719 0.33298