## 6.- Creating NumPy arrays

In [4]:
import numpy as np

def test_run():
  # list to 1D array
  print(np.array([(2,3,4), (5,6,7)]))

if __name__=="__main__":
  test_run()

[[2 3 4]
 [5 6 7]]


## 7.- Arrays with initial values

In [7]:
import numpy as np

def test_run():
  # Empty array
  #print(np.empty(5))
  #print(np.empty((5,4,3)))
  print(np.ones((5,4)))

if __name__=="__main__":
  test_run()

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 8.- Specify the datatype

In [8]:
import numpy as np

def test_run():
  # Array 1s
  print(np.ones((5,4), dtype=np.int_))

if __name__=="__main__":
  test_run()

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## 9.- Generating random numbers

In [4]:
import numpy as np

def test_run():
  # Array 1s
  #print(np.random.rand(5, 4))
  print(np.random.randint(10))
  print(np.random.randint(0, 10))
  print(np.random.randint(0, 10, size=5))
  print(np.random.randint(0, 10, size=(2,3)))

if __name__=="__main__":
  test_run()

5
2
[1 6 0 7 4]
[[2 8 2]
 [1 0 7]]


## 10.- Array atributes

In [5]:
import numpy as np

def test_run():
  # Array 1s
  a = np.random.random((5, 4))
  print(a.size)
  print(a.dtype)

if __name__=="__main__":
  test_run()

20
float64
